name: event_booking
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.2

dependencies:
  auto_size_text: ^3.0.0
  bloc: ^9.1.0
  connectivity_plus: ^7.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  json_serializable: ^6.11.1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.7.1
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  mockito: ^5.5.0
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
